name: Custom Build
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "Tag or committish for checkout."
        required: true
jobs:
  build-win:
    name: Build for Windows
    runs-on: windows-latest
    defaults:
      run:
        shell: c:\msys64\msys2_shell.cmd -defterm -no-start -here -mingw64 {0}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_WINDOWS_EXPORT_ALL_SYMBOLS=ON -DUSE_SHARED_MBEDTLS_LIBRARY=ON ..
        cmake --build . -t mbedcrypto --config Release
        cmake --build . -t mbedx509 --config Release
        cmake --build . -t mbedtls --config Release
    - name: Prepare Artifacts
      run: |
        mkdir win64
        cp build/library/Release/*.* win64/
        ls win64
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mbedtls-win64
        path: |
          win64/*.*
          include/
  build-linux:
    name: Build for Linux
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}
    - name: Generated Files
      run: |
        make generated_files
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SHARED_MBEDTLS_LIBRARY=ON ..
        cmake --build . -t mbedcrypto --config Release
        cmake --build . -t mbedx509 --config Release
        cmake --build . -t mbedtls --config Release
    - name: Prepare Artifacts
      run: |
        mkdir linux
        cp build/library/libmbed* linux/
        ls -lrt linux
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mbedtls-linux
        path: |
          linux/
          include/
  build-macos:
    name: Build for Macos
    runs-on: macos-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.ref }}
    - name: Generated Files
      run: |
        make generated_files
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DUSE_SHARED_MBEDTLS_LIBRARY=ON ..
        cmake --build . -t mbedcrypto --config Release
        cmake --build . -t mbedx509 --config Release
        cmake --build . -t mbedtls --config Release
    - name: Prepare Artifacts
      run: |
        mkdir macos
        cp build/library/libmbed* macos/
        ls -lrt  macos/
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: mbedtls-macos
        path: |
          macos/
          include/
